server:
  port: 5687


spring:
  data:
    mongodb:
      database: ---
      host: --
      port: 27017
      repositories:
        type: auto
#      username: asdf
#      password: fasdfsd



my-variable:
  name: 
  password:
    type: 
    value: 
